export const ITEMS = [
  {
    id: 1,
    name: 'T-shirt',
    location: 'Dressing-room',
    section: 'Right wardrobe',
    container: 'Hangers',
    description: 'Red T-shirt with dots in dressing-room',
  },
  {
    id: 2,
    name: 'T-shirt',
    location: 'Dressing-room',
    section: 'Right wardrobe',
    container: 'Hangers',
    description: 'Blue T-shirt with dots in dressing-room',
  },
  {
    id: 3,
    name: 'T-shirt',
    location: 'Dressing-room',
    section: 'Left wardrobe',
    container: 'Hangers',
    description: 'White T-shirt with dots in dressing-room',
  },
  {
    id: 4,
    name: 'T-shirt',
    location: 'Dressing-room',
    section: 'Left-wardrobe',
    container: 'Hangers',
    description: 'Yellow T-shirt with dots in dressing-room',
  },
  {
    id: 5,
    name: 'Jeans',
    location: 'Dressing-room',
    section: 'Dresser',
    container: 'First drawer',
    description: 'Blue Jeans',
  },
  {
    id: 6,
    name: 'Jacket',
    location: 'Dressing-room',
    section: 'Left-wardrobe',
    container: 'Hangers',
    description: 'Winter Jacket',
  },
  {
    id: 7,
    name: 'Tools',
    location: 'Garage',
    section: 'On the left shelf',
    container: 'Blue box',
    description: '',
  },
  {
    id: 8,
    name: 'Blue Tent',
    location: 'Basement',
    section: 'On the right shelf',
    container: 'Box number 3',
    description: '',
  },
];
